{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: v1
kind: List
items:
# ACI Connector Role (cluster wide)
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: "aci-connector"
  rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs:     ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs:     ["get","list","watch","create","patch","update","delete"]
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs:     ["get","list","watch","create","patch","update","delete"]
# ACI Connector Role Binding (cluster wide)
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: "aci-connector"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "aci-connector"
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: "{{ .Values.serviceAccount }}"
    namespace: "{{ .Release.Namespace }}"
{{ end }}
